spring:
  datasource:
    url: jdbc:h2:mem:temp;DB_CLOSE_ON_EXIT=FALSE
    hikari.username: sa
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    test-rollback-on-update: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          provider_class: org.hibernate.cache.EhCacheProvider
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          missing_cache_strategy: create