spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    test-rollback-on-update: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          provider_class: org.hibernate.cache.EhCacheProvider
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          missing_cache_strategy: create

logging:
  level:
    web: debug
server:
  tomcat:
    accesslog:
      enabled: true