spring:
  datasource:
    url: jdbc:h2:mem:temp;DB_CLOSE_ON_EXIT=FALSE
    hikari.username: sa
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    test-rollback-on-update: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true