spring:
  datasource:
    url: jdbc:h2:mem:temp
    hikari:
      username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true